name: CI

on:
  push:
    branches: [ main, work ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Materialize Gradle wrapper JAR
        run: ./.github/scripts/materialize-gradle-wrapper.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Build
        run: ./gradlew check
